name: Build and Deploy for using Chinese index
on:
    # Manual nightly & release
    workflow_dispatch:
        
run-name: Element Desktop
jobs:
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3

            - name: prepare
              id: prepare
              run: |
                  echo "version=$(cat package.json | jq -r .version)" >> $GITHUB_OUTPUT
                  echo "strDate=$(TZ=UTC-8 date +%Y-%m-%d)" >> $GITHUB_OUTPUT

            - name: Install Rust
              if: steps.cache.outputs.cache-hit != 'true'
              run: |
                  rustup toolchain install stable --profile minimal --no-self-update
                  rustup default stable
                  rustup target add aarch64-apple-darwin

            - uses: actions/setup-node@v3
              with:
                  cache: "yarn"

            # Does not need branch matching as only analyses this layer
            - name: Install Deps
              run: "yarn install --frozen-lockfile"

            - name: Fetch Element Web
              run: yarn run fetch --noverify -d "element.io/release/"

            - name: Build Natives
              run: "yarn build:native:universal"

            - name: "[Unsigned] Build App"
              run: |
                  scripts/generate-builder-config.ts 
                  yarn build:universal --publish never --config electron-builder.json
              env:
                  CSC_IDENTITY_AUTO_DISCOVERY: false

            - name: Upload release asset
              uses: svenstaro/upload-release-action@v2
              with:
                file: ./dist/*.dmg
                tag: v${{ steps.prepare.outputs.version }}-chinese
                file_glob: true
                overwrite: true
                release_name: v${{ steps.prepare.outputs.version }} ${{steps.prepare.outputs.strDate}} 编译
