name: Dockerbuild
on:
    workflow_dispatch: {}
    push:
        branches: [master, develop]
        paths:
            - "dockerbuild/**"
concurrency: ${{ github.workflow }}-${{ github.ref_name }}
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}-dockerbuild
jobs:
    build:
        name: Docker Build
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v3

            - name: Log in to the Container registry
              uses: docker/login-action@b4bedf8053341df3b5a9f9e0f2cf4e79e27360c6
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata for Docker
              id: meta
              uses: docker/metadata-action@879dcbb708d40f8b8679d4f7941b938a086e23a7
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=ref,event=branch

            - name: Build and push Docker image
              uses: docker/build-push-action@4c1b68d83ad20cc1a09620ca477d5bbbb5fa14d0
              with:
                  context: dockerbuild
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
