name: Dockerbuild
on:
    workflow_dispatch: {}
    push:
        branches: [master, staging, develop]
        paths:
            - "dockerbuild/**"
concurrency: ${{ github.workflow }}-${{ github.ref_name }}
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}-dockerbuild
jobs:
    build:
        name: Docker Build
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@5927c834f5b4fdf503fca6f4c7eccda82949e1ee # v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3
              with:
                  install: true

            - name: Log in to the Container registry
              uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata for Docker
              id: meta
              uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=ref,event=branch

            - name: Build and push Docker image
              uses: docker/build-push-action@1a162644f9a7e87d8f4b053101d1d9a712edc18c # v6
              with:
                  context: dockerbuild
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  platforms: linux/amd64,linux/arm64
