name: Dockerbuild
on:
    workflow_dispatch: {}
    push:
        branches: [master, develop]
        paths:
            - "dockerbuild/**"
concurrency: ${{ github.workflow }}-${{ github.ref_name }}
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}-dockerbuild
jobs:
    build:
        name: Docker Build
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata for Docker
              id: meta
              uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=ref,event=branch

            - name: Build and push Docker image
              uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5
              with:
                  context: dockerbuild
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
