name: Release Drafter
on:
    push:
        branches: [staging]
    workflow_dispatch: {}
    repository_dispatch:
        types: [upstream-release-notify]
concurrency: ${{ github.workflow }}
jobs:
    draft:
        uses: matrix-org/matrix-js-sdk/.github/workflows/release-drafter-workflow.yml@develop
        with:
            include-changes: element-hq/element-web~$VERSION
